/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_jgen_notes_api_core_JGenAPI */

#ifndef _Included_eu_jgen_notes_api_core_JGenAPI
#define _Included_eu_jgen_notes_api_core_JGenAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    addAssociation
 * Signature: (IIS)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_addAssociation
  (JNIEnv *, jobject, jint, jint, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    addObject
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_addObject
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_commit
  (JNIEnv *, jobject);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    countCardManyAsc
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_countCardManyAsc
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    countModelNameTypeObjs
 * Signature: (ISSLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_countModelNameTypeObjs
  (JNIEnv *, jobject, jint, jshort, jshort, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    countModelObjs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_countModelObjs
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    countModelTypeObjs
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_countModelTypeObjs
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    deleteAssociation
 * Signature: (IISZ)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_deleteAssociation
  (JNIEnv *, jobject, jint, jint, jshort, jboolean);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    deleteObject
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_deleteObject
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchModelObjs
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchModelObjs
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchModelTypeObjs
 * Signature: (ISI)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchModelTypeObjs
  (JNIEnv *, jobject, jint, jshort, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchModelObjListByNameType
 * Signature: (ISSLjava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchModelObjListByNameType
  (JNIEnv *, jobject, jint, jshort, jshort, jstring, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchModelNameTypeObjs
 * Signature: (ISSLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchModelNameTypeObjs
  (JNIEnv *, jobject, jint, jshort, jshort, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchCardManyAsc
 * Signature: (ISI)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchCardManyAsc
  (JNIEnv *, jobject, jint, jshort, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchCardOneAsc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchCardOneAsc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchCharArrayPrp
 * Signature: (IS)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchCharArrayPrp
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchModelInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchModelInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchOrderAscOccInfo
 * Signature: (ISI)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchOrderAscOccInfo
  (JNIEnv *, jobject, jint, jshort, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSingleCharPrp
 * Signature: (IS)C
 */
JNIEXPORT jchar JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSingleCharPrp
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSingleNumericPrp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSingleNumericPrp
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchObjectInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchObjectInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_open
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    reorderAssociationAftr
 * Signature: (SIII)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_reorderAssociationAftr
  (JNIEnv *, jobject, jshort, jint, jint, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    reorderAssociationBefr
 * Signature: (SIII)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_reorderAssociationBefr
  (JNIEnv *, jobject, jshort, jint, jint, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    rollback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_rollback
  (JNIEnv *, jobject);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    upCharArray
 * Signature: (ISLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_upCharArray
  (JNIEnv *, jobject, jint, jshort, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    upNumeric
 * Signature: (ISI)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_upNumeric
  (JNIEnv *, jobject, jint, jshort, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    upSingleChar
 * Signature: (ISC)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_upSingleChar
  (JNIEnv *, jobject, jint, jshort, jchar);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaObjTypeMnem
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaObjTypeMnem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    commitUpdates
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_commitUpdates
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    lock
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_lock
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    unlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_eu_jgen_notes_api_core_JGenAPI_unlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaObjTypeInfo
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaObjTypeInfo
  (JNIEnv *, jobject, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaObjTypeByMnem
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaObjTypeByMnem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaPrpTypeInfo
 * Signature: (SS)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaPrpTypeInfo
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaCharPrpDflt
 * Signature: (SS)C
 */
JNIEXPORT jchar JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaCharPrpDflt
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaIntPrpDflt
 * Signature: (SS)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaIntPrpDflt
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaPrpForObjType
 * Signature: (SI)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaPrpForObjType
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaAscTypeCodeInfo
 * Signature: (SS)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaAscTypeCodeInfo
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchSchemaAscForObjType
 * Signature: (SI)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchSchemaAscForObjType
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    countSchemaPrpForObjType
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_countSchemaPrpForObjType
  (JNIEnv *, jobject, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    countSchemaAscForObjType
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_countSchemaAscForObjType
  (JNIEnv *, jobject, jshort);

/*
 * Class:     eu_jgen_notes_api_core_JGenAPI
 * Method:    fetchModelByName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_jgen_notes_api_core_JGenAPI_fetchModelByName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
